// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/photo_repository/file/{userId}/{photoId}": {
            "get": {
                "tags": [
                    "photo_repository"
                ],
                "summary": "Returns file from storage",
                "operationId": "getPhotoFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Photo UUID",
                        "name": "photoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/photo_repository/upload": {
            "post": {
                "description": "Upload a photo_repository",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "photo_repository"
                ],
                "operationId": "uploadPhoto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "photo_repository data",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "photo_repository to be uploaded",
                        "name": "photo_repository",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/photo_repository/{userId}/{photoId}": {
            "delete": {
                "tags": [
                    "photo_repository"
                ],
                "summary": "Deletes a photo_repository",
                "operationId": "deletePhoto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Photo UUID",
                        "name": "photoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Storage Microservice API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
