info:
  contact: {}
  license:
    name: Apache 2.0
  title: Storage Microservice API
  version: "0.1"
paths:
  /photos/{userId}/{photoId}:
    delete:
      operationId: deletePhoto
      parameters:
      - description: Photo UUID
        in: path
        name: photoId
        required: true
        type: string
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      responses: {}
      summary: Deletes a photo_repository
      tags:
      - photo_repository
  /photos/file/{userId}/{photoId}:
    get:
      operationId: getPhotoFile
      parameters:
      - description: Photo UUID
        in: path
        name: photoId
        required: true
        type: string
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      responses: {}
      summary: Returns file from storage
      tags:
      - photo_repository
  /photos/get:
    get:
      operationId: getUserPhotos
      parameters:
      - description: User ID
        in: query
        name: userId
        required: true
        type: integer
      responses: {}
      summary: Returns ID of all user photos
      tags:
      - photo_repository
  /photos/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a photo_repository
      operationId: uploadPhoto
      parameters:
      - description: photo_repository data
        in: formData
        name: data
        required: true
        type: string
      - description: photo_repository to be uploaded
        in: formData
        name: photo_repository
        required: true
        type: file
      responses: {}
      tags:
      - photo_repository
swagger: "2.0"
