services:
  storage-service:
    build:
      context: .
      target: dev
    ports:
      - "8088:8080"
      - "40000:40000"
    environment:
      CONFIG_MINIO_ENDPOINT: storage-minio:9000
      CONFIG_MINIO_ACCESS_KEY: root
      CONFIG_MINIO_SECRET_KEY: password
      CONFIG_MONGODB_CONNECTION_STRING: mongodb://root:password@storage-db:27017
      CONFIG_KAFKA_ENDPOINT: kafka:9092
    depends_on:
      - kafka
      - storage-db
      - storage-minio
  storage-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: memoria-storage
  storage-minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
