include:
  - ../../compose.yml

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      CONFIG_MINIO_ENDPOINT: storage:9000
      CONFIG_MINIO_ACCESS_KEY: root
      CONFIG_MINIO_SECRET_KEY: password
      CONFIG_MONGODB_CONNECTION_STRING: mongodb://root:password@db:27017
    depends_on:
      - db
      - storage
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: memoria-storage
  storage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
